name: bitcoinconverter.build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.302

      - name: Install Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BitcoinConverter.Code.dll
          path: BitcoinConverter/bin/Release/net6.0/BitcoinConverter.Code.dll
